-- OpenMuse domain schema. This migration is additive and safe to replay only
-- through the migration runner (the runner records the version separately).
-- IDs are opaque text values generated by the application.

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  email text NOT NULL,
  name text,
  email_verified boolean NOT NULL DEFAULT false,
  image text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON users (lower(email));

CREATE TABLE IF NOT EXISTS workspaces (
  id text PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS workspaces_slug_idx ON workspaces (lower(slug));

CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  status text NOT NULL DEFAULT 'active',
  invited_by text REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id),
  CONSTRAINT workspace_members_role_check CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
  CONSTRAINT workspace_members_status_check CHECK (status IN ('active', 'suspended'))
);
CREATE INDEX IF NOT EXISTS workspace_members_user_idx ON workspace_members (user_id);

CREATE TABLE IF NOT EXISTS workspace_invites (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'member',
  token_hash text NOT NULL,
  invited_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT workspace_invites_role_check CHECK (role IN ('admin', 'member', 'viewer'))
);
CREATE UNIQUE INDEX IF NOT EXISTS workspace_invites_token_idx ON workspace_invites (token_hash);
CREATE INDEX IF NOT EXISTS workspace_invites_workspace_email_idx ON workspace_invites (workspace_id, lower(email));

CREATE TABLE IF NOT EXISTS conversations (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title text,
  visibility text NOT NULL DEFAULT 'private',
  status text NOT NULL DEFAULT 'active',
  archived_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversations_visibility_check CHECK (visibility IN ('private', 'workspace')),
  CONSTRAINT conversations_status_check CHECK (status IN ('active', 'archived'))
);
CREATE INDEX IF NOT EXISTS conversations_workspace_updated_idx ON conversations (workspace_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id text NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission text NOT NULL DEFAULT 'owner',
  added_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, user_id),
  CONSTRAINT conversation_members_permission_check CHECK (permission IN ('owner', 'viewer'))
);
CREATE INDEX IF NOT EXISTS conversation_members_user_idx ON conversation_members (user_id);

CREATE TABLE IF NOT EXISTS shared_snapshots (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  source_type text NOT NULL,
  source_id text NOT NULL,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS shared_snapshots_source_idx ON shared_snapshots (workspace_id, id);
CREATE INDEX IF NOT EXISTS shared_snapshots_workspace_created_idx ON shared_snapshots (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS shared_snapshot_grants (
  snapshot_id text NOT NULL REFERENCES shared_snapshots(id) ON DELETE CASCADE,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  granted_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (snapshot_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  conversation_id text NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  run_id text,
  author_id text REFERENCES users(id) ON DELETE SET NULL,
  role text NOT NULL,
  status text NOT NULL DEFAULT 'complete',
  sequence integer NOT NULL,
  content jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT messages_role_check CHECK (role IN ('system', 'user', 'assistant', 'tool'))
);
CREATE UNIQUE INDEX IF NOT EXISTS messages_conversation_sequence_idx ON messages (conversation_id, sequence);
CREATE INDEX IF NOT EXISTS messages_workspace_created_idx ON messages (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS runs (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  conversation_id text NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  requested_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'queued',
  provider text,
  idempotency_key text,
  lease_owner text,
  lease_token text,
  lease_expires_at timestamptz,
  heartbeat_at timestamptz,
  checkpoint jsonb,
  error jsonb,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT runs_status_check CHECK (status IN ('queued', 'running', 'waiting_approval', 'succeeded', 'failed', 'cancelled', 'outcome_unknown'))
);
CREATE UNIQUE INDEX IF NOT EXISTS runs_idempotency_idx ON runs (workspace_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS runs_claim_idx ON runs (status, lease_expires_at, created_at);
CREATE INDEX IF NOT EXISTS runs_workspace_idx ON runs (workspace_id, created_at);
ALTER TABLE messages
  ADD CONSTRAINT messages_run_id_fk FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS run_events (
  run_id text NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  sequence integer NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (run_id, sequence)
);
CREATE INDEX IF NOT EXISTS run_events_workspace_created_idx ON run_events (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS tasks (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  run_id text REFERENCES runs(id) ON DELETE CASCADE,
  requested_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  kind text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT now(),
  lease_owner text,
  fence_token text,
  lease_expires_at timestamptz,
  heartbeat_at timestamptz,
  checkpoint jsonb,
  last_error jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tasks_status_check CHECK (status IN ('queued', 'running', 'waiting_approval', 'succeeded', 'failed', 'cancelled', 'outcome_unknown'))
);
CREATE INDEX IF NOT EXISTS tasks_claim_idx ON tasks (status, available_at, lease_expires_at);
CREATE INDEX IF NOT EXISTS tasks_workspace_idx ON tasks (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS task_leases (
  task_id text PRIMARY KEY REFERENCES tasks(id) ON DELETE CASCADE,
  worker_id text NOT NULL,
  fence_token text NOT NULL,
  acquired_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  heartbeat_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS task_leases_fence_idx ON task_leases (fence_token);

CREATE TABLE IF NOT EXISTS artifacts (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  kind text NOT NULL,
  run_id text REFERENCES runs(id) ON DELETE SET NULL,
  name text NOT NULL DEFAULT 'artifact',
  storage_key text NOT NULL,
  content_type text,
  byte_size integer,
  checksum text,
  quarantined boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS artifacts_workspace_storage_idx ON artifacts (workspace_id, storage_key);
CREATE INDEX IF NOT EXISTS artifacts_workspace_created_idx ON artifacts (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS approvals (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  run_id text REFERENCES runs(id) ON DELETE CASCADE,
  requested_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  approved_by text REFERENCES users(id) ON DELETE SET NULL,
  action_type text NOT NULL,
  risk text NOT NULL DEFAULT 'external_side_effect',
  payload jsonb NOT NULL,
  payload_hash text NOT NULL,
  nonce text NOT NULL,
  digest text NOT NULL,
  tool_call_id text,
  policy_version text NOT NULL DEFAULT '1',
  connection_id text,
  target jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  expires_at timestamptz NOT NULL,
  decided_at timestamptz,
  consumed_at timestamptz,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT approvals_status_check CHECK (status IN ('pending', 'approved', 'denied', 'expired', 'executing', 'consumed', 'succeeded', 'failed', 'outcome_unknown'))
);
CREATE INDEX IF NOT EXISTS approvals_workspace_status_idx ON approvals (workspace_id, status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS approvals_run_payload_idx ON approvals (run_id, payload_hash) WHERE run_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS goals (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active',
  progress jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS goals_workspace_status_idx ON goals (workspace_id, status);

CREATE TABLE IF NOT EXISTS schedules (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  name text NOT NULL,
  cron text NOT NULL,
  timezone text NOT NULL DEFAULT 'UTC',
  enabled boolean NOT NULL DEFAULT true,
  task_kind text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  next_run_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS schedules_due_idx ON schedules (enabled, next_run_at);

CREATE TABLE IF NOT EXISTS memories (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  subject text,
  content text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS memories_workspace_subject_idx ON memories (workspace_id, subject);

CREATE TABLE IF NOT EXISTS connections (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  external_account_id text,
  status text NOT NULL DEFAULT 'active',
  scopes jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS connections_workspace_user_provider_account_idx ON connections (workspace_id, user_id, provider, external_account_id);
CREATE INDEX IF NOT EXISTS connections_workspace_provider_idx ON connections (workspace_id, provider);

CREATE TABLE IF NOT EXISTS provider_credentials (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id text REFERENCES users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  credential_kind text NOT NULL,
  encrypted_value text NOT NULL,
  key_version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS provider_credentials_scope_idx ON provider_credentials (workspace_id, user_id, provider, credential_kind);

CREATE TABLE IF NOT EXISTS audit_events (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_id text REFERENCES users(id) ON DELETE SET NULL,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_events_workspace_created_idx ON audit_events (workspace_id, created_at);

CREATE TABLE IF NOT EXISTS idempotency_records (
  key text NOT NULL,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_hash text NOT NULL,
  response_status integer,
  response_body jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (workspace_id, actor_id, key)
);

-- Better Auth persistence. These auth tables intentionally do not carry a
-- workspace context: a session lookup happens before the request has a
-- trusted workspace, and the random session token is the credential itself.
CREATE TABLE IF NOT EXISTS session (
  id text PRIMARY KEY,
  expires_at timestamptz NOT NULL,
  token text NOT NULL,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS session_token_idx ON session (token);
CREATE INDEX IF NOT EXISTS session_user_idx ON session (user_id);

CREATE TABLE IF NOT EXISTS account (
  id text PRIMARY KEY,
  account_id text NOT NULL,
  provider_id text NOT NULL,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  access_token text,
  refresh_token text,
  id_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  scope text,
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS account_provider_account_idx ON account (provider_id, account_id);
CREATE INDEX IF NOT EXISTS account_user_idx ON account (user_id);

CREATE TABLE IF NOT EXISTS verification (
  id text PRIMARY KEY,
  identifier text NOT NULL,
  value text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification (identifier);

-- Keep denormalized timestamps honest without making callers depend on a
-- particular ORM lifecycle hook.
CREATE OR REPLACE FUNCTION openmuse_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users', 'workspaces', 'workspace_members', 'conversations', 'messages',
    'runs', 'tasks', 'goals', 'schedules', 'memories', 'connections',
    'provider_credentials', 'session', 'account', 'verification'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', table_name || '_updated_at', table_name);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION openmuse_touch_updated_at()',
      table_name || '_updated_at', table_name
    );
  END LOOP;
END
$$;
